### ISSUE TITLE
BaseCSVField doesn't raise "required" error

### ISSUE THREAD

**Issue by neostimul** [carltongibson/django-filter#869]
I create the filter with required DateField.

```
class SomeFilter(filters.FilterSet):
    class Meta:
        model = Data
        fields = {
            'date': ('range', ),
        }
        filter_overrides = {
             models.DateField: {
                 'filter_class': filters.DateFilter,
                 'extra': lambda f: {
                     'required': True,
                 },
             },
         }
```
But on validation stage BaseCSVField doesn't raise the required error, cause value is None and it just returns None, without cleaning the base class

```
class BaseCSVField(forms.Field):
    ....

    def clean(self, value):
        if value is None:
--->        return None
        return [super(BaseCSVField, self).clean(v) for v in value]
```

**Comment by carltongibson** [comment]
Should be fixed by #854

**Comment by neostimul** [comment]
Yes, it fixed. Thank you

**Comment by neostimul** [comment]
No, i was wrong. BaseCSVField still does not raise required exception when date is not specified

when value is None (can be specified as None or not specified) must call clean value of Base class
```
    def clean(self, value):
        value = super(BaseRangeField, self).clean(value)
        if value is None:
            value = super(BaseCSVField, self).clean(value)
        return value
```
or we have not required error
